// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxlTgoPC_T3jtCRFPJB5wojiHIPN32174',
    appId: '1:976338726022:web:05723528d13b5fe80ef507',
    messagingSenderId: '976338726022',
    projectId: 'roadmate-b1551',
    // HAND-EDITED (a `flutterfire configure` re-run will revert this — put it
    // back): first-party auth domain so popup/redirect sign-in survives
    // browsers that partition third-party storage (Safari, incognito).
    // Requires https://roadmate.club/__/auth/handler in the Google OAuth
    // client's authorized redirect URIs (done 2026-07-07). Guarded by
    // test/firebase_options_test.dart.
    authDomain: 'roadmate.club',
    storageBucket: 'roadmate-b1551.firebasestorage.app',
    measurementId: 'G-4BZ3K6PC86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPLoikmH9I70WSKe_34hoXkn1gPrrmfYc',
    appId: '1:976338726022:android:3cf67620a8ab393b0ef507',
    messagingSenderId: '976338726022',
    projectId: 'roadmate-b1551',
    storageBucket: 'roadmate-b1551.firebasestorage.app',
  );

  // Hand-written from ios/Runner/GoogleService-Info.plist (the iOS Firebase app
  // is registered). Avoids the FlutterFire CLI's xcodeproj-gem step; runtime
  // init uses these explicit options, not the bundled plist.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAis-rD5arXcx188v7meVI0s17c8SQj4Wg',
    appId: '1:976338726022:ios:ed0f436d95f3e3e80ef507',
    messagingSenderId: '976338726022',
    projectId: 'roadmate-b1551',
    storageBucket: 'roadmate-b1551.firebasestorage.app',
    iosBundleId: 'com.darumatic.roadmate',
  );
}
