// Bumps the app version and keeps lib/version.dart in sync with pubspec.yaml.
//
//   dart run tool/bump_version.dart          # patch: 1.0.27+103 -> 1.0.28+104
//   dart run tool/bump_version.dart minor    # minor: 1.0.27+103 -> 1.1.0+104
//   dart run tool/bump_version.dart major    # major: 1.0.27+103 -> 2.0.0+104
//
// pubspec.yaml is the source of truth (marketing version + build number for the
// app stores). lib/version.dart holds the display-only marketing version that is
// compiled into the app.
import 'dart:io';

import 'package:roadmate/services/version_logic.dart';

final _pubspecVersion = RegExp(r'^version:\s*(\S+)\s*$', multiLine: true);

void main(List<String> args) {
  final part = switch (args) {
    [] => VersionPart.patch,
    [final name] when VersionPart.values.any((p) => p.name == name) =>
      VersionPart.values.byName(name),
    _ => null,
  };
  if (part == null) {
    stderr.writeln(
      'usage: dart run tool/bump_version.dart [patch|minor|major]',
    );
    exit(64);
  }

  final pubspecFile = File('pubspec.yaml');
  if (!pubspecFile.existsSync()) {
    stderr.writeln('pubspec.yaml not found — run from the project root.');
    exit(1);
  }

  final pubspec = pubspecFile.readAsStringSync();
  final match = _pubspecVersion.firstMatch(pubspec);
  if (match == null) {
    stderr.writeln('Could not find a "version:" line in pubspec.yaml.');
    exit(1);
  }

  final current = match.group(1)!;
  final next = bumpVersion(current, part: part);

  pubspecFile.writeAsStringSync(
    pubspec.replaceRange(match.start, match.end, 'version: $next'),
  );

  File('lib/version.dart').writeAsStringSync(
    '// GENERATED by tool/bump_version.dart — do not edit by hand.\n'
    "const String appVersion = '${marketingVersion(next)}';\n",
  );

  stdout.writeln('bumped $current -> $next');
}
