// Bumps the patch component of the app version and keeps lib/version.dart in
// sync with pubspec.yaml.
//
//   dart run tool/bump_version.dart
//
// pubspec.yaml is the source of truth (marketing version + build number for the
// app stores). lib/version.dart holds the display-only marketing version that is
// compiled into the app.
import 'dart:io';

import 'package:roadmate/services/version_logic.dart';

final _pubspecVersion = RegExp(r'^version:\s*(\S+)\s*$', multiLine: true);

void main() {
  final pubspecFile = File('pubspec.yaml');
  if (!pubspecFile.existsSync()) {
    stderr.writeln('pubspec.yaml not found — run from the project root.');
    exit(1);
  }

  final pubspec = pubspecFile.readAsStringSync();
  final match = _pubspecVersion.firstMatch(pubspec);
  if (match == null) {
    stderr.writeln('Could not find a "version:" line in pubspec.yaml.');
    exit(1);
  }

  final current = match.group(1)!;
  final next = bumpPatchVersion(current);

  pubspecFile.writeAsStringSync(
    pubspec.replaceRange(match.start, match.end, 'version: $next'),
  );

  File('lib/version.dart').writeAsStringSync(
    '// GENERATED by tool/bump_version.dart — do not edit by hand.\n'
    "const String appVersion = '${marketingVersion(next)}';\n",
  );

  stdout.writeln('bumped $current -> $next');
}
